class Assigns {
  static String useTemplate = 'Use Template';
  static String createEvent = 'CreateEvent';
  static String templateDes = 'Take advantage of 100+ go_to event patterns';
  static String createDes = 'Plan everything from scratch';
  static String selectOne = 'Selecte One!';
  static String selecteDetail =
      '''To select the right event management company, consider your specific event needs. Each company specializes in different aspects such as corporate events, parties, or festivals. Review their portfolios to see past events and client feedback''';
  static String popular = 'Top Popular Templates';
  static String selectedValue = 'Client';
  static String aboutUs = 'About Us';
  static String moreDetail = 'More Details';
  static String phoneNumber = 'Phone Number';
  static String otherLinks = 'Other Media Links';
  static String media = 'Media';
  static String website = 'Website:';
  static String component = 'Components';
  static String location = 'Location';
  static String budget = 'Budget';
  static String vendorName = 'VendorName:';
  static String submitDetails = 'Submit Details';
  static String clientInformation = 'Client Information';
  static String eventOverview = 'Event Overview';
  static String styleAndTheme = 'Style & Theme';
  static String guestList = 'Guest List';
  static String selectedVendors = 'Selected Vendors';
  static String totalAmount = 'Total Amount';
  static String date = 'Date:';
  static String time = 'Time:';
  static String guestCount = 'Guest Count:';
  static String totalAmoutn = 'Total Amount';
  static String name = 'Name:';
  static String email = 'Email:';
  static String phoneNumberdot = 'Phone Number:';
  static String eventDetail = 'Event Details';
  static String guestAndTheme = 'Guests & Theme';
  static String updateEvent = 'Update Event Details';
  static String placeHolderImage = 'assets/images/place holder.jpg';
}
